---
name: johnsy.com
url: https://www.johnsy.com
description: "Pete Johns (/piːt ʤɒnz/ - he/him/his): Human being; just like you."
description_html: |
  Pete Johns (<a href="https://namedrop.io/petejohns"><em>/piːt ʤɒnz/</em></a> -
  <a href="https://pronouns.org/he">he/him/his</a>): Human being; just like you.
keywords:
  - Pete Johns
  - Peter Johns
  - paj
  - johnsy
  - johnsyweb
  - pajLog
  - johnsy.com
  - parkrun
  - software engineer
  - web developer
  - open source
  - blogger
  - tech enthusiast
  - runner
  - cyclist
  - photographer
  - traveller
  - Melbourne
  - Australia

author:
  name: Pete Johns
  given_name: Pete
  family_name: Johns
  pronunciation: /piːt ʤɒnz/
  pronouns: he/him/his
  bio: Human being; just like you
  job_title: Head of Engineering
  url: https://www.johnsy.com/contact/
  avatar: https://www.johnsy.com/images/johnsyweb.png
  social_profiles:
    - https://github.com/johnsyweb
    - https://www.flickr.com/people/johnsyweb/

apple_touch_icon_sizes:
  - 57
  - 60
  - 72
  - 76
  - 114
  - 120
  - 144
  - 152

permalink: /blog/:year/:month/:day/:title/
paginate: 10
paginate_path: "blog/page:num/"
hilighter: pygments

exclude:
  - ".*"
  - ".*/"
  - "Gemfile*"
  - "package*.json"
  - LICENSE
  - README.md
  - node_modules/
  - scripts/
  - tmp/
  - vendor/
  - .lighthouseci/
  - .lighthouserc*.json
  - pnpm-lock.yaml

plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji

whitelist:
  - jekyll-redirect-from
